/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import javax.swing.JOptionPane;

/**
 *
 * @author t-bye-
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
        Reports.setVisible(false);
        Home.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Reports = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        Home = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel57 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel59 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(91, 78, 121));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(118, 119, 132));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 90));

        jPanel10.setBackground(new java.awt.Color(4, 6, 70));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel10MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel10MouseReleased(evt);
            }
        });
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Microsoft Himalaya", 0, 55)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("HOME");
        jLabel4.setToolTipText("");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel4MouseReleased(evt);
            }
        });
        jPanel10.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 120, -1));

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 220, 80));

        jPanel13.setBackground(new java.awt.Color(4, 6, 70));

        jLabel1.setFont(new java.awt.Font("Microsoft Himalaya", 0, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GRAPHS");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 220, -1));

        jPanel17.setBackground(new java.awt.Color(4, 6, 70));

        jLabel3.setFont(new java.awt.Font("Microsoft Himalaya", 0, 45)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NOTIFICATION");
        jLabel3.setToolTipText("");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jPanel2.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 220, -1));

        jPanel16.setBackground(new java.awt.Color(4, 6, 70));
        jPanel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel16MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel16MouseReleased(evt);
            }
        });
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft Himalaya", 0, 55)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("REPORTS");
        jLabel2.setToolTipText("");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });
        jPanel16.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 180, -1));

        jPanel2.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 220, 70));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Settings-icon.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 50, 60));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/disconnect_logout.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 550));

        Reports.setBackground(new java.awt.Color(153, 153, 153));
        Reports.setName("Reports_Panel"); // NOI18N
        Reports.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(5, 9, 131));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        Reports.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 40));

        jPanel5.setBackground(new java.awt.Color(192, 193, 196));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Microsoft Himalaya", 0, 60)); // NOI18N
        jLabel5.setText("REPORTS");
        jLabel5.setToolTipText("");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, 50));

        jLabel6.setFont(new java.awt.Font("Microsoft Himalaya", 0, 30)); // NOI18N
        jLabel6.setText("This will provide your data for creating solutions and decisions in implementing actions");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        Reports.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 940, 90));

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setName(""); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("jLabel7");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, 350, -1, -1));
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/temperature-icon.png"))); // NOI18N
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 90));

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Microsoft Himalaya", 0, 20)); // NOI18N
        jLabel9.setText("- This will not affects fishes inside the fond");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 20));

        jLabel10.setFont(new java.awt.Font("Microsoft Himalaya", 0, 20)); // NOI18N
        jLabel10.setText("- The fish can be producted at this temperature");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        jLabel21.setFont(new java.awt.Font("Microsoft Himalaya", 0, 20)); // NOI18N
        jLabel21.setText("- The reading of temperature today is 35°");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 330, 70));

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Microsoft Himalaya", 0, 35)); // NOI18N
        jLabel24.setText("35°C");
        jPanel11.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jPanel7.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 70, 40));

        jLabel16.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        jLabel16.setText("WQMD FINDINGS:");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, -1, -1));

        jLabel17.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel17.setText("Reading");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ph.png"))); // NOI18N
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel19.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel19.setText("Temperature");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel20.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel20.setText("pH");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Microsoft Himalaya", 0, 20)); // NOI18N
        jLabel22.setText("- The water is contaminated with feeds");
        jPanel12.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        jLabel25.setFont(new java.awt.Font("Microsoft Himalaya", 0, 20)); // NOI18N
        jLabel25.setText("- People are not able to drink this water");
        jPanel12.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        jPanel7.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 330, 60));

        jPanel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Microsoft Himalaya", 0, 35)); // NOI18N
        jLabel29.setText("6.5 pH");
        jPanel14.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jPanel7.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 80, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/oxygen.png"))); // NOI18N
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jPanel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Microsoft Himalaya", 0, 20)); // NOI18N
        jLabel23.setText("- There are no effects in the environment");
        jPanel15.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        jLabel26.setFont(new java.awt.Font("Microsoft Himalaya", 0, 20)); // NOI18N
        jLabel26.setText("- Oxygen in the water is normal");
        jPanel15.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        jPanel7.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 330, 60));

        jLabel27.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel27.setText("Reading");
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel28.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel28.setText("Oxygen ");
        jPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jPanel18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Microsoft Himalaya", 0, 30)); // NOI18N
        jLabel15.setText("7.55 ppm");
        jPanel18.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 30));

        jPanel7.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 80, 40));

        jPanel19.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 340, 110));

        jPanel20.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, -1, -1));

        jLabel30.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel30.setText("Reading");
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel31.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        jLabel31.setText("WQMD SUGGESTS:");
        jPanel7.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, -1, -1));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 930, 410));

        Reports.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 940, 420));
        jPanel6.getAccessibleContext().setAccessibleName("");

        jPanel1.add(Reports, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 940, -1));
        Reports.getAccessibleContext().setAccessibleName("Reports_Panel");

        Home.setBackground(new java.awt.Color(153, 153, 153));
        Home.setName("Reports_Panel"); // NOI18N
        Home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel22.setBackground(new java.awt.Color(5, 9, 131));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Microsoft Himalaya", 1, 40)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("STATUS:");
        jLabel32.setToolTipText("");
        jPanel22.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, -1, 50));

        jLabel58.setFont(new java.awt.Font("Microsoft Himalaya", 1, 40)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("INFORMATION PORTAL");
        jLabel58.setToolTipText("");
        jPanel22.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        jLabel61.setFont(new java.awt.Font("Microsoft Himalaya", 1, 35)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(0, 176, 2));
        jLabel61.setText("Active");
        jPanel22.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, -1, 30));

        Home.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 40));

        jPanel23.setBackground(new java.awt.Color(255, 181, 179));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel60.setFont(new java.awt.Font("Microsoft Himalaya", 1, 35)); // NOI18N
        jLabel60.setText("Time of Reading:");
        jPanel23.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel64.setFont(new java.awt.Font("Microsoft Himalaya", 1, 35)); // NOI18N
        jLabel64.setText("Date of Reading:");
        jPanel23.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel67.setFont(new java.awt.Font("Microsoft Himalaya", 1, 35)); // NOI18N
        jLabel67.setText("Location:");
        jPanel23.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        Home.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 940, 90));

        jPanel24.setBackground(new java.awt.Color(153, 153, 153));
        jPanel24.setName(""); // NOI18N
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setText("jLabel7");
        jPanel25.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, 350, -1, -1));
        jPanel25.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/temperature-icon.png"))); // NOI18N
        jPanel25.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 90));

        jPanel26.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Microsoft Himalaya", 0, 20)); // NOI18N
        jLabel37.setText("- This will not affects fishes inside the fond");
        jPanel26.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 20));

        jLabel38.setFont(new java.awt.Font("Microsoft Himalaya", 0, 20)); // NOI18N
        jLabel38.setText("- The fish can be producted at this temperature");
        jPanel26.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        jLabel39.setFont(new java.awt.Font("Microsoft Himalaya", 0, 20)); // NOI18N
        jLabel39.setText("- The reading of temperature today is 35°");
        jPanel26.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        jPanel25.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 330, 70));

        jPanel27.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setFont(new java.awt.Font("Microsoft Himalaya", 0, 35)); // NOI18N
        jLabel40.setText("35°C");
        jPanel27.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jPanel25.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 70, 40));

        jLabel42.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel42.setText("Reading");
        jPanel25.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ph.png"))); // NOI18N
        jPanel25.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel44.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel44.setText("Temperature");
        jPanel25.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel45.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel45.setText("pH");
        jPanel25.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jPanel28.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setFont(new java.awt.Font("Microsoft Himalaya", 0, 20)); // NOI18N
        jLabel46.setText("- The water is contaminated with feeds");
        jPanel28.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        jLabel47.setFont(new java.awt.Font("Microsoft Himalaya", 0, 20)); // NOI18N
        jLabel47.setText("- People are not able to drink this water");
        jPanel28.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        jPanel25.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 330, 60));

        jPanel29.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setFont(new java.awt.Font("Microsoft Himalaya", 0, 35)); // NOI18N
        jLabel48.setText("6.5 pH");
        jPanel29.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jPanel25.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 80, 40));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/oxygen.png"))); // NOI18N
        jPanel25.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jPanel30.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setFont(new java.awt.Font("Microsoft Himalaya", 0, 20)); // NOI18N
        jLabel50.setText("- There are no effects in the environment");
        jPanel30.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        jLabel51.setFont(new java.awt.Font("Microsoft Himalaya", 0, 20)); // NOI18N
        jLabel51.setText("- Oxygen in the water is normal");
        jPanel30.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        jPanel25.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 330, 60));

        jLabel53.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel53.setText("Oxygen ");
        jPanel25.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jPanel31.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel54.setFont(new java.awt.Font("Microsoft Himalaya", 0, 30)); // NOI18N
        jLabel54.setText("7.55 ppm");
        jPanel31.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 30));

        jPanel25.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 80, 40));

        jLabel55.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel55.setText("Reading");
        jPanel25.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel66.setFont(new java.awt.Font("Microsoft Himalaya", 1, 35)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(51, 102, 255));
        jLabel66.setText("Reports");
        jPanel25.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel68.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        jLabel68.setText("Reading");
        jPanel25.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jPanel24.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 410));

        jPanel34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel62.setText("jLabel7");
        jPanel34.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, 350, -1, -1));
        jPanel34.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        jLabel65.setFont(new java.awt.Font("Microsoft Himalaya", 1, 35)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(51, 102, 255));
        jLabel65.setText("Overview");
        jPanel34.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Quality-icon.png"))); // NOI18N
        jPanel34.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setFont(new java.awt.Font("Microsoft Himalaya", 1, 48)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 157, 2));
        jLabel41.setText("Normal");
        jPanel3.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

        jPanel34.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 150, 50));

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Environmental.png"))); // NOI18N
        jPanel34.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jScrollPane1.setAutoscrolls(true);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("- The water did not affect any water species in the area");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel34.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 250, 60));

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/health-risk.png"))); // NOI18N
        jPanel34.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("- Fish will not be affected");
        jScrollPane2.setViewportView(jTextArea2);

        jPanel34.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 250, 50));

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/economic icon.png"))); // NOI18N
        jPanel34.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel52.setFont(new java.awt.Font("Microsoft Himalaya", 1, 15)); // NOI18N
        jLabel52.setText("Economical Status");
        jPanel34.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jLabel69.setFont(new java.awt.Font("Microsoft Himalaya", 1, 15)); // NOI18N
        jLabel69.setText("Water Quality");
        jPanel34.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel70.setFont(new java.awt.Font("Microsoft Himalaya", 1, 15)); // NOI18N
        jLabel70.setText("Environmental Effects");
        jPanel34.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        jLabel71.setFont(new java.awt.Font("Microsoft Himalaya", 1, 15)); // NOI18N
        jLabel71.setText("Heart Risk");
        jPanel34.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText("- Fish economics will gain more profit and the production will be high");
        jScrollPane3.setViewportView(jTextArea3);

        jPanel34.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 250, 70));

        jPanel24.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 450, 410));

        Home.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 940, 420));

        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 940, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MousePressed
     Home.setVisible(true);
     Reports.setVisible(false);
    }//GEN-LAST:event_jPanel10MousePressed

    private void jPanel16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel16MousePressed
     Home.setVisible(false);
     Reports.setVisible(true);
    }//GEN-LAST:event_jPanel16MousePressed

    private void jLabel4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseReleased
     Home.setVisible(true);
     Reports.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseReleased

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
     Home.setVisible(false);
     Reports.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseReleased

    private void jPanel10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseReleased
     Home.setVisible(true);
     Reports.setVisible(false);
    }//GEN-LAST:event_jPanel10MouseReleased

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
     Home.setVisible(true);
     Reports.setVisible(false);
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
    Home.setVisible(false);
    Reports.setVisible(true);
    }//GEN-LAST:event_jLabel2MousePressed

    private void jPanel16MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel16MouseReleased
    Home.setVisible(false);
    Reports.setVisible(true);
    }//GEN-LAST:event_jPanel16MouseReleased

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
    Security_pass sp = new Security_pass();
        int x = JOptionPane.showConfirmDialog(null, "Confirm Exit!","Close",JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
               if(x==JOptionPane.YES_OPTION){
                dispose();
                sp.setVisible(true);
//                  System.exit(0);
               }
    }//GEN-LAST:event_jLabel13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Home;
    private javax.swing.JPanel Reports;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
